version: "3.9"

services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"

  tests:
    build:
      context: ./tests

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_home:
